---
abstract: 'We love beer and sushi'
author:
  - 'Songmu <y.songmu@gmail.com>'
build_requires:
  Capture::Tiny: '0'
  Test::Fatal: '0'
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v1.0.0, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-BeerSushi
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Acme::BeerSushi:
    file: lib/Acme/BeerSushi.pm
    version: '0.01'
  Acme::BeerSushi::CLI:
    file: lib/Acme/BeerSushi/CLI.pm
  Acme::BeerSushi::CLI::Encode:
    file: lib/Acme/BeerSushi/CLI/Encode.pm
requires:
  Encode: '0'
  Getopt::Long: '2.39'
  Module::Load: '0'
  Mouse: '0'
  Mouse::Util::TypeConstraints: '0'
  Path::Tiny: '0'
  String::CamelCase: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/Songmu/p5-Acme-BeerSushi/issues
  homepage: https://github.com/Songmu/p5-Acme-BeerSushi
  repository: git://github.com/Songmu/p5-Acme-BeerSushi.git
version: '0.01'
x_authority: cpan:SONGMU
